server {
    listen 80;
    server_name topheightselectricals.com www.topheightselectricals.com;

    root /var/www/topheights/frontend;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
